name: build push and deploy image

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]


permissions:
            contents: read # to checkout code
            id-token: write # to assume role in AWS
env:
    AWS_REGION: us-east-1
    AWS_ACTION_ROLE: ${{ secrets.AWS_ACTION_ROLE }}
    ECR_REPO_NAME: dev
    IMAGE_TAG: ${{ github.run_number }} 

jobs:
    build:
        runs-on: ubuntu-latest #github-hosted runner
        
        steps:
          - name: clone repo
            uses: actions/checkout@v3
          - name: AWS creds config
            uses: aws-actions/configure-aws-credentials@v3
            with:
               role-to-assume: ${{ env.AWS_ACTION_ROLE }}   #Open ID connect 
               aws-region: ${{ env.AWS_REGION }}
          - name: Login to ECR
            uses: aws-actions/amazon-ecr-login@v1 
            id: ecr-login
          - name: Bulid and tag 
            id: build-and-push
            run: |
                docker build -t ${{steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{env.IMAGE_TAG}} .

          - name: Scan docker Image for vulnerabilities
            uses: aquasecurity/trivy-action@master
            with:
                image-ref: "${{steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{env.IMAGE_TAG}}"  # Scans the built image
                format: "table"
                exit-code: "0"
                severity: "CRITICAL,HIGH"
          - name: Push image to ECR
            run: |
                docker push ${{steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{env.IMAGE_TAG}}
           
          - name: Store image in github env
            run: echo "IMAGE=${{steps.ecr-login.outputs.registry }}/${{ env.ECR_REPO_NAME }}:${{env.IMAGE_TAG}}" >> $GITHUB_ENV
    Deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Deploy to ECS
            uses: aws-actions/amazon-ecs-deploy-task-definition@v1
            with:
                task-definition: ecs-task-def.json # Path to your ECS task definition file
                service: my-ecs-service # Name of your ECS service
                cluster: my-ecs-cluster # Name of your ECS cluster
                wait-for-service-stability: true
                image: ${{ env.IMAGE }} # Image from the build job            