name: build push and deploy image
on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

env:
    AWS_REGION: us-east-1
    AWS_ACTION_ROLE: ${{ secrets.AWS_ACTION_ROLE }}

jobs:
    build:
        runs-on: ubuntu-latest #github-hosted runner
        steps:
          - name: clone repo
            uses: actions/checkout@v3
          - name: AWS creds config
            uses: aws-actions/configure-aws-credentials@v3
            with:
               role-to-assume: ${{ env.AWS_ACTION_ROLE }}   #Open ID connect 
               aws-region: ${{ env.AWS_REGION }}
          - name: Login to ECR
            uses: aws-actions/amazon-ecr-login@v1 
    
    
